// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

type Instance struct {
	ID               string
	Pid              int64
	Port             int64
	WorkingDirectory string
	Status           string
	CreatedAt        string
	UpdatedAt        string
}

type OrchestratorSession struct {
	ID             string
	InstanceID     string
	SessionID      string
	HeartbeatCount int64
	LastHeartbeatAt string
	Status         string
	CreatedAt      string
	UpdatedAt      string
}

type Session struct {
	ID         string
	InstanceID string
	Title      string
	Status     string
	CreatedAt  string
	UpdatedAt  string
}

type Task struct {
	ID             string
	InstanceID     string
	IssueNumber    int64
	IssueUrl       string
	Title          string
	Status         string
	SessionID      string
	BranchName     string
	PrUrl          string
	LastActivityAt string
	CreatedAt      string
	UpdatedAt      string
}
