// Code generated by sqlc. DO NOT EDIT.

package sqlc

type Instance struct {
	ID               string
	Pid              int64
	Port             int64
	WorkingDirectory string
	Status           string
	CreatedAt        string
	UpdatedAt        string
}

type Session struct {
	ID         string
	InstanceID string
	Title      string
	Status     string
	CreatedAt  string
	UpdatedAt  string
}
