// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type AuthSession struct {
	Token     string
	Username  string
	CreatedAt string
	ExpiresAt string
}

type CrossRepoTask struct {
	ID              string
	ParentTaskID    string
	ChildTaskID     string
	ChildInstanceID string
	Status          string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type FlockAgentSession struct {
	ID               string
	SessionID        string
	WorkingDirectory string
	Status           string
	CreatedAt        string
	UpdatedAt        string
}

type Instance struct {
	ID               string
	Pid              int64
	Port             int64
	WorkingDirectory string
	Status           string
	CreatedAt        string
	UpdatedAt        string
	HeartbeatHash    string
	Org              string
	Repo             string
}

type MemoryIndexMetum struct {
	Path        string
	Category    string
	Title       string
	Tags        string
	ContentHash string
	IndexedAt   string
	UpdatedAt   string
}

type MemorySearchIndex struct {
	Path     string
	Title    string
	Category string
	Tags     string
	Content  string
}

type MemoryVersion struct {
	ID          string
	Path        string
	Version     int64
	Content     string
	ContentHash string
	Author      string
	Reason      string
	CreatedAt   string
}

type OrchestratorSession struct {
	ID              string
	InstanceID      string
	SessionID       string
	HeartbeatCount  int64
	Status          string
	CreatedAt       string
	UpdatedAt       string
	LastHeartbeatAt string
}

type PrSet struct {
	ID              string
	GroupName       string
	Status          string
	DeploymentOrder sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type PrSetMember struct {
	ID         string
	PrSetID    string
	InstanceID string
	Org        string
	Repo       string
	PrUrl      string
	PrNumber   int64
	Status     string
	MergeOrder int64
	MergedAt   sql.NullTime
	CreatedAt  time.Time
}

type RepoManifest struct {
	ID              string
	InstanceID      string
	Org             string
	Repo            string
	GroupName       string
	ManifestJson    string
	Valid           bool
	ValidationError sql.NullString
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type Session struct {
	ID         string
	InstanceID string
	Title      string
	Status     string
	CreatedAt  string
	UpdatedAt  string
	ParentID   string
	Model      sql.NullString
}

type Task struct {
	ID             string
	InstanceID     string
	IssueNumber    int64
	IssueUrl       string
	Title          string
	Status         string
	SessionID      string
	BranchName     string
	PrUrl          string
	LastActivityAt string
	CreatedAt      string
	UpdatedAt      string
}

type TestFailure struct {
	ID             string
	InstanceID     string
	SessionID      sql.NullString
	Framework      string
	TestName       string
	FilePath       sql.NullString
	AssertionText  sql.NullString
	StackTrace     sql.NullString
	InputValues    sql.NullString
	ErrorMessage   string
	CodeChanges    sql.NullString
	Resolved       bool
	ResolvedAt     sql.NullTime
	FixDescription sql.NullString
	FixDiff        sql.NullString
	CreatedAt      time.Time
}

type WorktreeHealthCheck struct {
	ID                    string
	WorktreeID            string
	Status                string
	GitFsckOk             int64
	HasUncommittedChanges int64
	DiskUsageBytes        int64
	ErrorMessage          string
	CheckedAt             string
}

type WorktreeMetadatum struct {
	ID                    string
	InstanceID            string
	BranchName            string
	WorktreePath          string
	IssueNumber           int64
	AgentSessionID        string
	Status                string
	DeletionReason        string
	DiskUsageBytes        int64
	HasUncommittedChanges int64
	LastActivityAt        string
	CreatedAt             string
	UpdatedAt             string
	DeletedAt             string
}
