// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
)

const createInstance = `-- name: CreateInstance :one
INSERT INTO instances (id, pid, port, working_directory, status)
VALUES (?, ?, ?, ?, ?)
RETURNING id, pid, port, working_directory, status, created_at, updated_at
`

type CreateInstanceParams struct {
	ID               string
	Pid              int64
	Port             int64
	WorkingDirectory string
	Status           string
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error) {
	row := q.db.QueryRowContext(ctx, createInstance,
		arg.ID,
		arg.Pid,
		arg.Port,
		arg.WorkingDirectory,
		arg.Status,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Port,
		&i.WorkingDirectory,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, instance_id, title, status)
VALUES (?, ?, ?, ?)
RETURNING id, instance_id, title, status, created_at, updated_at
`

type CreateSessionParams struct {
	ID         string
	InstanceID string
	Title      string
	Status     string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.InstanceID,
		arg.Title,
		arg.Status,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteInstance = `-- name: DeleteInstance :exec
DELETE FROM instances WHERE id = ?
`

func (q *Queries) DeleteInstance(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteInstance, id)
	return err
}

const deleteSessionsByInstance = `-- name: DeleteSessionsByInstance :exec
DELETE FROM sessions WHERE instance_id = ?
`

func (q *Queries) DeleteSessionsByInstance(ctx context.Context, instanceID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByInstance, instanceID)
	return err
}

const getInstance = `-- name: GetInstance :one
SELECT id, pid, port, working_directory, status, created_at, updated_at FROM instances WHERE id = ?
`

func (q *Queries) GetInstance(ctx context.Context, id string) (Instance, error) {
	row := q.db.QueryRowContext(ctx, getInstance, id)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Port,
		&i.WorkingDirectory,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, instance_id, title, status, created_at, updated_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInstances = `-- name: ListInstances :many
SELECT id, pid, port, working_directory, status, created_at, updated_at FROM instances ORDER BY created_at DESC
`

func (q *Queries) ListInstances(ctx context.Context) ([]Instance, error) {
	rows, err := q.db.QueryContext(ctx, listInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.Pid,
			&i.Port,
			&i.WorkingDirectory,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByInstance = `-- name: ListSessionsByInstance :many
SELECT id, instance_id, title, status, created_at, updated_at FROM sessions WHERE instance_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListSessionsByInstance(ctx context.Context, instanceID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsForRestore = `-- name: ListSessionsForRestore :many
SELECT id, instance_id, title, status FROM sessions WHERE instance_id = ? AND status != 'stopped' ORDER BY created_at DESC
`

type ListSessionsForRestoreRow struct {
	ID         string
	InstanceID string
	Title      string
	Status     string
}

func (q *Queries) ListSessionsForRestore(ctx context.Context, instanceID string) ([]ListSessionsForRestoreRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsForRestore, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionsForRestoreRow
	for rows.Next() {
		var i ListSessionsForRestoreRow
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Title,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStaleInstancesStopped = `-- name: MarkStaleInstancesStopped :exec
UPDATE instances SET status = 'stopped', updated_at = datetime('now') WHERE status IN ('starting', 'running')
`

func (q *Queries) MarkStaleInstancesStopped(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markStaleInstancesStopped)
	return err
}

const updateInstancePort = `-- name: UpdateInstancePort :exec
UPDATE instances SET port = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateInstancePortParams struct {
	Port int64
	ID   string
}

func (q *Queries) UpdateInstancePort(ctx context.Context, arg UpdateInstancePortParams) error {
	_, err := q.db.ExecContext(ctx, updateInstancePort, arg.Port, arg.ID)
	return err
}

const updateInstanceStatus = `-- name: UpdateInstanceStatus :exec
UPDATE instances SET status = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateInstanceStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateInstanceStatus(ctx context.Context, arg UpdateInstanceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateInstanceStatus, arg.Status, arg.ID)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE sessions SET status = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateSessionStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionStatus, arg.Status, arg.ID)
	return err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (id, instance_id, title, status)
VALUES (?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  title = excluded.title,
  updated_at = datetime('now')
`

type UpsertSessionParams struct {
	ID         string
	InstanceID string
	Title      string
	Status     string
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSession,
		arg.ID,
		arg.InstanceID,
		arg.Title,
		arg.Status,
	)
	return err
}
