// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countActiveTasksByInstance = `-- name: CountActiveTasksByInstance :one
SELECT COUNT(*) FROM tasks WHERE instance_id = ? AND status IN ('pending', 'active')
`

func (q *Queries) CountActiveTasksByInstance(ctx context.Context, instanceID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countActiveTasksByInstance, instanceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAllActiveTasks = `-- name: CountAllActiveTasks :one
SELECT COUNT(*) FROM tasks WHERE status IN ('pending', 'active')
`

func (q *Queries) CountAllActiveTasks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAllActiveTasks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFailuresByTestName = `-- name: CountFailuresByTestName :one
SELECT COUNT(*) FROM test_failures
WHERE instance_id = ? AND test_name = ?
`

type CountFailuresByTestNameParams struct {
	InstanceID string
	TestName   string
}

func (q *Queries) CountFailuresByTestName(ctx context.Context, arg CountFailuresByTestNameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFailuresByTestName, arg.InstanceID, arg.TestName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthSession = `-- name: CreateAuthSession :one

INSERT INTO auth_sessions (token, username, expires_at)
VALUES (?, ?, datetime('now', '+7 days'))
RETURNING token, username, created_at, expires_at
`

type CreateAuthSessionParams struct {
	Token    string
	Username string
}

// Auth session queries
func (q *Queries) CreateAuthSession(ctx context.Context, arg CreateAuthSessionParams) (AuthSession, error) {
	row := q.db.QueryRowContext(ctx, createAuthSession, arg.Token, arg.Username)
	var i AuthSession
	err := row.Scan(
		&i.Token,
		&i.Username,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const createCrossRepoTask = `-- name: CreateCrossRepoTask :one

INSERT INTO cross_repo_tasks (id, parent_task_id, child_task_id, child_instance_id)
VALUES (?, ?, ?, ?)
RETURNING id, parent_task_id, child_task_id, child_instance_id, status, created_at, updated_at
`

type CreateCrossRepoTaskParams struct {
	ID              string
	ParentTaskID    string
	ChildTaskID     string
	ChildInstanceID string
}

// Cross-repo task queries
func (q *Queries) CreateCrossRepoTask(ctx context.Context, arg CreateCrossRepoTaskParams) (CrossRepoTask, error) {
	row := q.db.QueryRowContext(ctx, createCrossRepoTask,
		arg.ID,
		arg.ParentTaskID,
		arg.ChildTaskID,
		arg.ChildInstanceID,
	)
	var i CrossRepoTask
	err := row.Scan(
		&i.ID,
		&i.ParentTaskID,
		&i.ChildTaskID,
		&i.ChildInstanceID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createFlockAgentSession = `-- name: CreateFlockAgentSession :one

INSERT INTO flock_agent_sessions (id, session_id, working_directory, status)
VALUES (?, ?, ?, 'active')
RETURNING id, session_id, working_directory, status, created_at, updated_at
`

type CreateFlockAgentSessionParams struct {
	ID               string
	SessionID        string
	WorkingDirectory string
}

// Flock agent session queries
func (q *Queries) CreateFlockAgentSession(ctx context.Context, arg CreateFlockAgentSessionParams) (FlockAgentSession, error) {
	row := q.db.QueryRowContext(ctx, createFlockAgentSession, arg.ID, arg.SessionID, arg.WorkingDirectory)
	var i FlockAgentSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.WorkingDirectory,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createHealthCheck = `-- name: CreateHealthCheck :one
INSERT INTO worktree_health_checks (id, worktree_id, status, git_fsck_ok, has_uncommitted_changes, disk_usage_bytes, error_message)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, worktree_id, status, git_fsck_ok, has_uncommitted_changes, disk_usage_bytes, error_message, checked_at
`

type CreateHealthCheckParams struct {
	ID                    string
	WorktreeID            string
	Status                string
	GitFsckOk             int64
	HasUncommittedChanges int64
	DiskUsageBytes        int64
	ErrorMessage          string
}

func (q *Queries) CreateHealthCheck(ctx context.Context, arg CreateHealthCheckParams) (WorktreeHealthCheck, error) {
	row := q.db.QueryRowContext(ctx, createHealthCheck,
		arg.ID,
		arg.WorktreeID,
		arg.Status,
		arg.GitFsckOk,
		arg.HasUncommittedChanges,
		arg.DiskUsageBytes,
		arg.ErrorMessage,
	)
	var i WorktreeHealthCheck
	err := row.Scan(
		&i.ID,
		&i.WorktreeID,
		&i.Status,
		&i.GitFsckOk,
		&i.HasUncommittedChanges,
		&i.DiskUsageBytes,
		&i.ErrorMessage,
		&i.CheckedAt,
	)
	return i, err
}

const createInstance = `-- name: CreateInstance :one
INSERT INTO instances (id, pid, port, working_directory, status, org, repo)
VALUES (?, 0, 0, ?, 'running', ?, ?)
RETURNING id, pid, port, working_directory, status, created_at, updated_at, heartbeat_hash, org, repo
`

type CreateInstanceParams struct {
	ID               string
	WorkingDirectory string
	Org              string
	Repo             string
}

func (q *Queries) CreateInstance(ctx context.Context, arg CreateInstanceParams) (Instance, error) {
	row := q.db.QueryRowContext(ctx, createInstance,
		arg.ID,
		arg.WorkingDirectory,
		arg.Org,
		arg.Repo,
	)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Port,
		&i.WorkingDirectory,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeartbeatHash,
		&i.Org,
		&i.Repo,
	)
	return i, err
}

const createOrchestratorSession = `-- name: CreateOrchestratorSession :one

INSERT INTO orchestrator_sessions (id, instance_id, session_id, status)
VALUES (?, ?, ?, 'active')
RETURNING id, instance_id, session_id, heartbeat_count, status, created_at, updated_at, last_heartbeat_at
`

type CreateOrchestratorSessionParams struct {
	ID         string
	InstanceID string
	SessionID  string
}

// Orchestrator session queries
func (q *Queries) CreateOrchestratorSession(ctx context.Context, arg CreateOrchestratorSessionParams) (OrchestratorSession, error) {
	row := q.db.QueryRowContext(ctx, createOrchestratorSession, arg.ID, arg.InstanceID, arg.SessionID)
	var i OrchestratorSession
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.SessionID,
		&i.HeartbeatCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastHeartbeatAt,
	)
	return i, err
}

const createPRSet = `-- name: CreatePRSet :one

INSERT INTO pr_sets (id, group_name, deployment_order)
VALUES (?, ?, ?)
RETURNING id, group_name, status, deployment_order, created_at, updated_at
`

type CreatePRSetParams struct {
	ID              string
	GroupName       string
	DeploymentOrder sql.NullString
}

// PR set queries
func (q *Queries) CreatePRSet(ctx context.Context, arg CreatePRSetParams) (PrSet, error) {
	row := q.db.QueryRowContext(ctx, createPRSet, arg.ID, arg.GroupName, arg.DeploymentOrder)
	var i PrSet
	err := row.Scan(
		&i.ID,
		&i.GroupName,
		&i.Status,
		&i.DeploymentOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPRSetMember = `-- name: CreatePRSetMember :one
INSERT INTO pr_set_members (id, pr_set_id, instance_id, org, repo, pr_url, pr_number, merge_order)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, pr_set_id, instance_id, org, repo, pr_url, pr_number, status, merge_order, merged_at, created_at
`

type CreatePRSetMemberParams struct {
	ID         string
	PrSetID    string
	InstanceID string
	Org        string
	Repo       string
	PrUrl      string
	PrNumber   int64
	MergeOrder int64
}

func (q *Queries) CreatePRSetMember(ctx context.Context, arg CreatePRSetMemberParams) (PrSetMember, error) {
	row := q.db.QueryRowContext(ctx, createPRSetMember,
		arg.ID,
		arg.PrSetID,
		arg.InstanceID,
		arg.Org,
		arg.Repo,
		arg.PrUrl,
		arg.PrNumber,
		arg.MergeOrder,
	)
	var i PrSetMember
	err := row.Scan(
		&i.ID,
		&i.PrSetID,
		&i.InstanceID,
		&i.Org,
		&i.Repo,
		&i.PrUrl,
		&i.PrNumber,
		&i.Status,
		&i.MergeOrder,
		&i.MergedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, instance_id, title, status)
VALUES (?, ?, ?, ?)
RETURNING id, instance_id, title, status, created_at, updated_at, parent_id, model
`

type CreateSessionParams struct {
	ID         string
	InstanceID string
	Title      string
	Status     string
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession,
		arg.ID,
		arg.InstanceID,
		arg.Title,
		arg.Status,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Model,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one

INSERT INTO tasks (id, instance_id, issue_number, issue_url, title, status, session_id, branch_name)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, instance_id, issue_number, issue_url, title, status, session_id, branch_name, pr_url, last_activity_at, created_at, updated_at
`

type CreateTaskParams struct {
	ID          string
	InstanceID  string
	IssueNumber int64
	IssueUrl    string
	Title       string
	Status      string
	SessionID   string
	BranchName  string
}

// Task queries
func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.InstanceID,
		arg.IssueNumber,
		arg.IssueUrl,
		arg.Title,
		arg.Status,
		arg.SessionID,
		arg.BranchName,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.IssueNumber,
		&i.IssueUrl,
		&i.Title,
		&i.Status,
		&i.SessionID,
		&i.BranchName,
		&i.PrUrl,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTestFailure = `-- name: CreateTestFailure :one

INSERT INTO test_failures (id, instance_id, session_id, framework, test_name, file_path, assertion_text, stack_trace, input_values, error_message, code_changes)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, instance_id, session_id, framework, test_name, file_path, assertion_text, stack_trace, input_values, error_message, code_changes, resolved, resolved_at, fix_description, fix_diff, created_at
`

type CreateTestFailureParams struct {
	ID            string
	InstanceID    string
	SessionID     sql.NullString
	Framework     string
	TestName      string
	FilePath      sql.NullString
	AssertionText sql.NullString
	StackTrace    sql.NullString
	InputValues   sql.NullString
	ErrorMessage  string
	CodeChanges   sql.NullString
}

// Test failure queries
func (q *Queries) CreateTestFailure(ctx context.Context, arg CreateTestFailureParams) (TestFailure, error) {
	row := q.db.QueryRowContext(ctx, createTestFailure,
		arg.ID,
		arg.InstanceID,
		arg.SessionID,
		arg.Framework,
		arg.TestName,
		arg.FilePath,
		arg.AssertionText,
		arg.StackTrace,
		arg.InputValues,
		arg.ErrorMessage,
		arg.CodeChanges,
	)
	var i TestFailure
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.SessionID,
		&i.Framework,
		&i.TestName,
		&i.FilePath,
		&i.AssertionText,
		&i.StackTrace,
		&i.InputValues,
		&i.ErrorMessage,
		&i.CodeChanges,
		&i.Resolved,
		&i.ResolvedAt,
		&i.FixDescription,
		&i.FixDiff,
		&i.CreatedAt,
	)
	return i, err
}

const createWorktreeMetadata = `-- name: CreateWorktreeMetadata :one

INSERT INTO worktree_metadata (id, instance_id, branch_name, worktree_path, issue_number, agent_session_id)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, instance_id, branch_name, worktree_path, issue_number, agent_session_id, status, deletion_reason, disk_usage_bytes, has_uncommitted_changes, last_activity_at, created_at, updated_at, deleted_at
`

type CreateWorktreeMetadataParams struct {
	ID             string
	InstanceID     string
	BranchName     string
	WorktreePath   string
	IssueNumber    int64
	AgentSessionID string
}

// Worktree metadata queries
func (q *Queries) CreateWorktreeMetadata(ctx context.Context, arg CreateWorktreeMetadataParams) (WorktreeMetadatum, error) {
	row := q.db.QueryRowContext(ctx, createWorktreeMetadata,
		arg.ID,
		arg.InstanceID,
		arg.BranchName,
		arg.WorktreePath,
		arg.IssueNumber,
		arg.AgentSessionID,
	)
	var i WorktreeMetadatum
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.BranchName,
		&i.WorktreePath,
		&i.IssueNumber,
		&i.AgentSessionID,
		&i.Status,
		&i.DeletionReason,
		&i.DiskUsageBytes,
		&i.HasUncommittedChanges,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAuthSession = `-- name: DeleteAuthSession :exec
DELETE FROM auth_sessions WHERE token = ?
`

func (q *Queries) DeleteAuthSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteAuthSession, token)
	return err
}

const deleteExpiredAuthSessions = `-- name: DeleteExpiredAuthSessions :exec
DELETE FROM auth_sessions WHERE expires_at <= datetime('now')
`

func (q *Queries) DeleteExpiredAuthSessions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredAuthSessions)
	return err
}

const deleteInstance = `-- name: DeleteInstance :exec
DELETE FROM instances WHERE id = ?
`

func (q *Queries) DeleteInstance(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteInstance, id)
	return err
}

const deleteOrchestratorSessionsByInstance = `-- name: DeleteOrchestratorSessionsByInstance :exec
DELETE FROM orchestrator_sessions WHERE instance_id = ?
`

func (q *Queries) DeleteOrchestratorSessionsByInstance(ctx context.Context, instanceID string) error {
	_, err := q.db.ExecContext(ctx, deleteOrchestratorSessionsByInstance, instanceID)
	return err
}

const deleteRepoManifest = `-- name: DeleteRepoManifest :exec
DELETE FROM repo_manifests WHERE id = ?
`

func (q *Queries) DeleteRepoManifest(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRepoManifest, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const deleteSessionsByInstance = `-- name: DeleteSessionsByInstance :exec
DELETE FROM sessions WHERE instance_id = ?
`

func (q *Queries) DeleteSessionsByInstance(ctx context.Context, instanceID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByInstance, instanceID)
	return err
}

const deleteTasksByInstance = `-- name: DeleteTasksByInstance :exec
DELETE FROM tasks WHERE instance_id = ?
`

func (q *Queries) DeleteTasksByInstance(ctx context.Context, instanceID string) error {
	_, err := q.db.ExecContext(ctx, deleteTasksByInstance, instanceID)
	return err
}

const ensureFlockAgentInstance = `-- name: EnsureFlockAgentInstance :exec
INSERT OR IGNORE INTO instances (id, pid, port, working_directory, status, org, repo)
VALUES ('flock-agent', 0, 0, '', 'running', '', '')
`

func (q *Queries) EnsureFlockAgentInstance(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ensureFlockAgentInstance)
	return err
}

const getActiveFlockAgentSession = `-- name: GetActiveFlockAgentSession :one
SELECT id, session_id, working_directory, status, created_at, updated_at FROM flock_agent_sessions WHERE status = 'active' LIMIT 1
`

func (q *Queries) GetActiveFlockAgentSession(ctx context.Context) (FlockAgentSession, error) {
	row := q.db.QueryRowContext(ctx, getActiveFlockAgentSession)
	var i FlockAgentSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.WorkingDirectory,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveFlockAgentSessionByInstance = `-- name: GetActiveFlockAgentSessionByInstance :one
SELECT id, instance_id, title, status, created_at, updated_at, parent_id, model FROM sessions WHERE instance_id = 'flock-agent' AND status = 'active' LIMIT 1
`

func (q *Queries) GetActiveFlockAgentSessionByInstance(ctx context.Context) (Session, error) {
	row := q.db.QueryRowContext(ctx, getActiveFlockAgentSessionByInstance)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Model,
	)
	return i, err
}

const getActiveOrchestratorSession = `-- name: GetActiveOrchestratorSession :one
SELECT id, instance_id, session_id, heartbeat_count, status, created_at, updated_at, last_heartbeat_at FROM orchestrator_sessions
WHERE instance_id = ? AND status = 'active'
LIMIT 1
`

func (q *Queries) GetActiveOrchestratorSession(ctx context.Context, instanceID string) (OrchestratorSession, error) {
	row := q.db.QueryRowContext(ctx, getActiveOrchestratorSession, instanceID)
	var i OrchestratorSession
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.SessionID,
		&i.HeartbeatCount,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastHeartbeatAt,
	)
	return i, err
}

const getAuthSession = `-- name: GetAuthSession :one
SELECT token, username, created_at, expires_at FROM auth_sessions WHERE token = ? AND expires_at > datetime('now')
`

func (q *Queries) GetAuthSession(ctx context.Context, token string) (AuthSession, error) {
	row := q.db.QueryRowContext(ctx, getAuthSession, token)
	var i AuthSession
	err := row.Scan(
		&i.Token,
		&i.Username,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const getFlockAgentSession = `-- name: GetFlockAgentSession :one
SELECT id, session_id, working_directory, status, created_at, updated_at FROM flock_agent_sessions WHERE id = ?
`

func (q *Queries) GetFlockAgentSession(ctx context.Context, id string) (FlockAgentSession, error) {
	row := q.db.QueryRowContext(ctx, getFlockAgentSession, id)
	var i FlockAgentSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.WorkingDirectory,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstance = `-- name: GetInstance :one
SELECT id, pid, port, working_directory, status, created_at, updated_at, heartbeat_hash, org, repo FROM instances WHERE id = ?
`

func (q *Queries) GetInstance(ctx context.Context, id string) (Instance, error) {
	row := q.db.QueryRowContext(ctx, getInstance, id)
	var i Instance
	err := row.Scan(
		&i.ID,
		&i.Pid,
		&i.Port,
		&i.WorkingDirectory,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HeartbeatHash,
		&i.Org,
		&i.Repo,
	)
	return i, err
}

const getInstanceHeartbeatHash = `-- name: GetInstanceHeartbeatHash :one
SELECT heartbeat_hash FROM instances WHERE id = ?
`

func (q *Queries) GetInstanceHeartbeatHash(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRowContext(ctx, getInstanceHeartbeatHash, id)
	var heartbeat_hash string
	err := row.Scan(&heartbeat_hash)
	return heartbeat_hash, err
}

const getLastHeartbeatByInstance = `-- name: GetLastHeartbeatByInstance :one
SELECT last_heartbeat_at FROM orchestrator_sessions
WHERE instance_id = ? AND status = 'active'
ORDER BY last_heartbeat_at DESC
LIMIT 1
`

func (q *Queries) GetLastHeartbeatByInstance(ctx context.Context, instanceID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getLastHeartbeatByInstance, instanceID)
	var last_heartbeat_at string
	err := row.Scan(&last_heartbeat_at)
	return last_heartbeat_at, err
}

const getLatestHealthCheck = `-- name: GetLatestHealthCheck :one
SELECT id, worktree_id, status, git_fsck_ok, has_uncommitted_changes, disk_usage_bytes, error_message, checked_at FROM worktree_health_checks
WHERE worktree_id = ?
ORDER BY checked_at DESC
LIMIT 1
`

func (q *Queries) GetLatestHealthCheck(ctx context.Context, worktreeID string) (WorktreeHealthCheck, error) {
	row := q.db.QueryRowContext(ctx, getLatestHealthCheck, worktreeID)
	var i WorktreeHealthCheck
	err := row.Scan(
		&i.ID,
		&i.WorktreeID,
		&i.Status,
		&i.GitFsckOk,
		&i.HasUncommittedChanges,
		&i.DiskUsageBytes,
		&i.ErrorMessage,
		&i.CheckedAt,
	)
	return i, err
}

const getPRSet = `-- name: GetPRSet :one
SELECT id, group_name, status, deployment_order, created_at, updated_at FROM pr_sets WHERE id = ?
`

func (q *Queries) GetPRSet(ctx context.Context, id string) (PrSet, error) {
	row := q.db.QueryRowContext(ctx, getPRSet, id)
	var i PrSet
	err := row.Scan(
		&i.ID,
		&i.GroupName,
		&i.Status,
		&i.DeploymentOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoManifest = `-- name: GetRepoManifest :one
SELECT id, instance_id, org, repo, group_name, manifest_json, valid, validation_error, created_at, updated_at FROM repo_manifests WHERE instance_id = ? AND org = ? AND repo = ?
`

type GetRepoManifestParams struct {
	InstanceID string
	Org        string
	Repo       string
}

func (q *Queries) GetRepoManifest(ctx context.Context, arg GetRepoManifestParams) (RepoManifest, error) {
	row := q.db.QueryRowContext(ctx, getRepoManifest, arg.InstanceID, arg.Org, arg.Repo)
	var i RepoManifest
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Org,
		&i.Repo,
		&i.GroupName,
		&i.ManifestJson,
		&i.Valid,
		&i.ValidationError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoManifestByID = `-- name: GetRepoManifestByID :one
SELECT id, instance_id, org, repo, group_name, manifest_json, valid, validation_error, created_at, updated_at FROM repo_manifests WHERE id = ?
`

func (q *Queries) GetRepoManifestByID(ctx context.Context, id string) (RepoManifest, error) {
	row := q.db.QueryRowContext(ctx, getRepoManifestByID, id)
	var i RepoManifest
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Org,
		&i.Repo,
		&i.GroupName,
		&i.ManifestJson,
		&i.Valid,
		&i.ValidationError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, instance_id, title, status, created_at, updated_at, parent_id, model FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ParentID,
		&i.Model,
	)
	return i, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, instance_id, issue_number, issue_url, title, status, session_id, branch_name, pr_url, last_activity_at, created_at, updated_at FROM tasks WHERE id = ?
`

func (q *Queries) GetTaskByID(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.IssueNumber,
		&i.IssueUrl,
		&i.Title,
		&i.Status,
		&i.SessionID,
		&i.BranchName,
		&i.PrUrl,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskByIssue = `-- name: GetTaskByIssue :one
SELECT id, instance_id, issue_number, issue_url, title, status, session_id, branch_name, pr_url, last_activity_at, created_at, updated_at FROM tasks WHERE instance_id = ? AND issue_number = ?
`

type GetTaskByIssueParams struct {
	InstanceID  string
	IssueNumber int64
}

func (q *Queries) GetTaskByIssue(ctx context.Context, arg GetTaskByIssueParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, getTaskByIssue, arg.InstanceID, arg.IssueNumber)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.IssueNumber,
		&i.IssueUrl,
		&i.Title,
		&i.Status,
		&i.SessionID,
		&i.BranchName,
		&i.PrUrl,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTestFailure = `-- name: GetTestFailure :one
SELECT id, instance_id, session_id, framework, test_name, file_path, assertion_text, stack_trace, input_values, error_message, code_changes, resolved, resolved_at, fix_description, fix_diff, created_at FROM test_failures WHERE id = ?
`

func (q *Queries) GetTestFailure(ctx context.Context, id string) (TestFailure, error) {
	row := q.db.QueryRowContext(ctx, getTestFailure, id)
	var i TestFailure
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.SessionID,
		&i.Framework,
		&i.TestName,
		&i.FilePath,
		&i.AssertionText,
		&i.StackTrace,
		&i.InputValues,
		&i.ErrorMessage,
		&i.CodeChanges,
		&i.Resolved,
		&i.ResolvedAt,
		&i.FixDescription,
		&i.FixDiff,
		&i.CreatedAt,
	)
	return i, err
}

const getWorktreeByBranch = `-- name: GetWorktreeByBranch :one
SELECT id, instance_id, branch_name, worktree_path, issue_number, agent_session_id, status, deletion_reason, disk_usage_bytes, has_uncommitted_changes, last_activity_at, created_at, updated_at, deleted_at FROM worktree_metadata
WHERE instance_id = ? AND branch_name = ? AND status = 'active'
LIMIT 1
`

type GetWorktreeByBranchParams struct {
	InstanceID string
	BranchName string
}

func (q *Queries) GetWorktreeByBranch(ctx context.Context, arg GetWorktreeByBranchParams) (WorktreeMetadatum, error) {
	row := q.db.QueryRowContext(ctx, getWorktreeByBranch, arg.InstanceID, arg.BranchName)
	var i WorktreeMetadatum
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.BranchName,
		&i.WorktreePath,
		&i.IssueNumber,
		&i.AgentSessionID,
		&i.Status,
		&i.DeletionReason,
		&i.DiskUsageBytes,
		&i.HasUncommittedChanges,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getWorktreeByID = `-- name: GetWorktreeByID :one
SELECT id, instance_id, branch_name, worktree_path, issue_number, agent_session_id, status, deletion_reason, disk_usage_bytes, has_uncommitted_changes, last_activity_at, created_at, updated_at, deleted_at FROM worktree_metadata WHERE id = ?
`

func (q *Queries) GetWorktreeByID(ctx context.Context, id string) (WorktreeMetadatum, error) {
	row := q.db.QueryRowContext(ctx, getWorktreeByID, id)
	var i WorktreeMetadatum
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.BranchName,
		&i.WorktreePath,
		&i.IssueNumber,
		&i.AgentSessionID,
		&i.Status,
		&i.DeletionReason,
		&i.DiskUsageBytes,
		&i.HasUncommittedChanges,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrementHeartbeatCount = `-- name: IncrementHeartbeatCount :exec
UPDATE orchestrator_sessions
SET heartbeat_count = heartbeat_count + 1, last_heartbeat_at = datetime('now', 'utc'), updated_at = datetime('now', 'utc')
WHERE id = ?
`

func (q *Queries) IncrementHeartbeatCount(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementHeartbeatCount, id)
	return err
}

const listAbandonedWorktrees = `-- name: ListAbandonedWorktrees :many
SELECT id, instance_id, branch_name, worktree_path, issue_number, agent_session_id, status, deletion_reason, disk_usage_bytes, has_uncommitted_changes, last_activity_at, created_at, updated_at, deleted_at FROM worktree_metadata
WHERE instance_id = ? AND status = 'active'
AND last_activity_at < datetime('now', 'utc', '-24 hours')
ORDER BY last_activity_at ASC
`

func (q *Queries) ListAbandonedWorktrees(ctx context.Context, instanceID string) ([]WorktreeMetadatum, error) {
	rows, err := q.db.QueryContext(ctx, listAbandonedWorktrees, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorktreeMetadatum
	for rows.Next() {
		var i WorktreeMetadatum
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.BranchName,
			&i.WorktreePath,
			&i.IssueNumber,
			&i.AgentSessionID,
			&i.Status,
			&i.DeletionReason,
			&i.DiskUsageBytes,
			&i.HasUncommittedChanges,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveTasks = `-- name: ListActiveTasks :many
SELECT id, instance_id, issue_number, issue_url, title, status, session_id, branch_name, pr_url, last_activity_at, created_at, updated_at FROM tasks WHERE instance_id = ? AND status IN ('pending', 'active') ORDER BY created_at ASC
`

func (q *Queries) ListActiveTasks(ctx context.Context, instanceID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listActiveTasks, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.IssueNumber,
			&i.IssueUrl,
			&i.Title,
			&i.Status,
			&i.SessionID,
			&i.BranchName,
			&i.PrUrl,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveWorktrees = `-- name: ListActiveWorktrees :many
SELECT id, instance_id, branch_name, worktree_path, issue_number, agent_session_id, status, deletion_reason, disk_usage_bytes, has_uncommitted_changes, last_activity_at, created_at, updated_at, deleted_at FROM worktree_metadata
WHERE instance_id = ? AND status = 'active'
ORDER BY created_at ASC
`

func (q *Queries) ListActiveWorktrees(ctx context.Context, instanceID string) ([]WorktreeMetadatum, error) {
	rows, err := q.db.QueryContext(ctx, listActiveWorktrees, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorktreeMetadatum
	for rows.Next() {
		var i WorktreeMetadatum
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.BranchName,
			&i.WorktreePath,
			&i.IssueNumber,
			&i.AgentSessionID,
			&i.Status,
			&i.DeletionReason,
			&i.DiskUsageBytes,
			&i.HasUncommittedChanges,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllManifests = `-- name: ListAllManifests :many
SELECT id, instance_id, org, repo, group_name, manifest_json, valid, validation_error, created_at, updated_at FROM repo_manifests ORDER BY group_name, org, repo
`

func (q *Queries) ListAllManifests(ctx context.Context) ([]RepoManifest, error) {
	rows, err := q.db.QueryContext(ctx, listAllManifests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoManifest
	for rows.Next() {
		var i RepoManifest
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Org,
			&i.Repo,
			&i.GroupName,
			&i.ManifestJson,
			&i.Valid,
			&i.ValidationError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllWorktrees = `-- name: ListAllWorktrees :many
SELECT id, instance_id, branch_name, worktree_path, issue_number, agent_session_id, status, deletion_reason, disk_usage_bytes, has_uncommitted_changes, last_activity_at, created_at, updated_at, deleted_at FROM worktree_metadata
WHERE instance_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListAllWorktrees(ctx context.Context, instanceID string) ([]WorktreeMetadatum, error) {
	rows, err := q.db.QueryContext(ctx, listAllWorktrees, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorktreeMetadatum
	for rows.Next() {
		var i WorktreeMetadatum
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.BranchName,
			&i.WorktreePath,
			&i.IssueNumber,
			&i.AgentSessionID,
			&i.Status,
			&i.DeletionReason,
			&i.DiskUsageBytes,
			&i.HasUncommittedChanges,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletedTasks = `-- name: ListCompletedTasks :many
SELECT id, instance_id, issue_number, issue_url, title, status, session_id, branch_name, pr_url, last_activity_at, created_at, updated_at FROM tasks WHERE instance_id = ? AND status = 'completed' ORDER BY updated_at ASC
`

func (q *Queries) ListCompletedTasks(ctx context.Context, instanceID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listCompletedTasks, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.IssueNumber,
			&i.IssueUrl,
			&i.Title,
			&i.Status,
			&i.SessionID,
			&i.BranchName,
			&i.PrUrl,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrossRepoTasksByChild = `-- name: ListCrossRepoTasksByChild :many
SELECT id, parent_task_id, child_task_id, child_instance_id, status, created_at, updated_at FROM cross_repo_tasks WHERE child_task_id = ?
`

func (q *Queries) ListCrossRepoTasksByChild(ctx context.Context, childTaskID string) ([]CrossRepoTask, error) {
	rows, err := q.db.QueryContext(ctx, listCrossRepoTasksByChild, childTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrossRepoTask
	for rows.Next() {
		var i CrossRepoTask
		if err := rows.Scan(
			&i.ID,
			&i.ParentTaskID,
			&i.ChildTaskID,
			&i.ChildInstanceID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCrossRepoTasksByParent = `-- name: ListCrossRepoTasksByParent :many
SELECT id, parent_task_id, child_task_id, child_instance_id, status, created_at, updated_at FROM cross_repo_tasks WHERE parent_task_id = ? ORDER BY created_at
`

func (q *Queries) ListCrossRepoTasksByParent(ctx context.Context, parentTaskID string) ([]CrossRepoTask, error) {
	rows, err := q.db.QueryContext(ctx, listCrossRepoTasksByParent, parentTaskID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CrossRepoTask
	for rows.Next() {
		var i CrossRepoTask
		if err := rows.Scan(
			&i.ID,
			&i.ParentTaskID,
			&i.ChildTaskID,
			&i.ChildInstanceID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailedTasks = `-- name: ListFailedTasks :many
SELECT id, instance_id, issue_number, issue_url, title, status, session_id, branch_name, pr_url, last_activity_at, created_at, updated_at FROM tasks WHERE instance_id = ? AND status IN ('failed', 'stuck') ORDER BY last_activity_at ASC
`

func (q *Queries) ListFailedTasks(ctx context.Context, instanceID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listFailedTasks, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.IssueNumber,
			&i.IssueUrl,
			&i.Title,
			&i.Status,
			&i.SessionID,
			&i.BranchName,
			&i.PrUrl,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailuresByFramework = `-- name: ListFailuresByFramework :many
SELECT id, instance_id, session_id, framework, test_name, file_path, assertion_text, stack_trace, input_values, error_message, code_changes, resolved, resolved_at, fix_description, fix_diff, created_at FROM test_failures
WHERE instance_id = ? AND framework = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListFailuresByFrameworkParams struct {
	InstanceID string
	Framework  string
	Limit      int64
}

func (q *Queries) ListFailuresByFramework(ctx context.Context, arg ListFailuresByFrameworkParams) ([]TestFailure, error) {
	rows, err := q.db.QueryContext(ctx, listFailuresByFramework, arg.InstanceID, arg.Framework, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestFailure
	for rows.Next() {
		var i TestFailure
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.SessionID,
			&i.Framework,
			&i.TestName,
			&i.FilePath,
			&i.AssertionText,
			&i.StackTrace,
			&i.InputValues,
			&i.ErrorMessage,
			&i.CodeChanges,
			&i.Resolved,
			&i.ResolvedAt,
			&i.FixDescription,
			&i.FixDiff,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFailuresByTestName = `-- name: ListFailuresByTestName :many
SELECT id, instance_id, session_id, framework, test_name, file_path, assertion_text, stack_trace, input_values, error_message, code_changes, resolved, resolved_at, fix_description, fix_diff, created_at FROM test_failures
WHERE test_name = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListFailuresByTestNameParams struct {
	TestName string
	Limit    int64
}

func (q *Queries) ListFailuresByTestName(ctx context.Context, arg ListFailuresByTestNameParams) ([]TestFailure, error) {
	rows, err := q.db.QueryContext(ctx, listFailuresByTestName, arg.TestName, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestFailure
	for rows.Next() {
		var i TestFailure
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.SessionID,
			&i.Framework,
			&i.TestName,
			&i.FilePath,
			&i.AssertionText,
			&i.StackTrace,
			&i.InputValues,
			&i.ErrorMessage,
			&i.CodeChanges,
			&i.Resolved,
			&i.ResolvedAt,
			&i.FixDescription,
			&i.FixDiff,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHealthChecksByWorktree = `-- name: ListHealthChecksByWorktree :many
SELECT id, worktree_id, status, git_fsck_ok, has_uncommitted_changes, disk_usage_bytes, error_message, checked_at FROM worktree_health_checks
WHERE worktree_id = ?
ORDER BY checked_at DESC
LIMIT 10
`

func (q *Queries) ListHealthChecksByWorktree(ctx context.Context, worktreeID string) ([]WorktreeHealthCheck, error) {
	rows, err := q.db.QueryContext(ctx, listHealthChecksByWorktree, worktreeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []WorktreeHealthCheck
	for rows.Next() {
		var i WorktreeHealthCheck
		if err := rows.Scan(
			&i.ID,
			&i.WorktreeID,
			&i.Status,
			&i.GitFsckOk,
			&i.HasUncommittedChanges,
			&i.DiskUsageBytes,
			&i.ErrorMessage,
			&i.CheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstances = `-- name: ListInstances :many
SELECT id, pid, port, working_directory, status, created_at, updated_at, heartbeat_hash, org, repo FROM instances WHERE id != 'flock-agent' ORDER BY created_at DESC
`

func (q *Queries) ListInstances(ctx context.Context) ([]Instance, error) {
	rows, err := q.db.QueryContext(ctx, listInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(
			&i.ID,
			&i.Pid,
			&i.Port,
			&i.WorkingDirectory,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.HeartbeatHash,
			&i.Org,
			&i.Repo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listManifestsByGroup = `-- name: ListManifestsByGroup :many
SELECT id, instance_id, org, repo, group_name, manifest_json, valid, validation_error, created_at, updated_at FROM repo_manifests WHERE group_name = ? ORDER BY org, repo
`

func (q *Queries) ListManifestsByGroup(ctx context.Context, groupName string) ([]RepoManifest, error) {
	rows, err := q.db.QueryContext(ctx, listManifestsByGroup, groupName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RepoManifest
	for rows.Next() {
		var i RepoManifest
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Org,
			&i.Repo,
			&i.GroupName,
			&i.ManifestJson,
			&i.Valid,
			&i.ValidationError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPRSetMembers = `-- name: ListPRSetMembers :many
SELECT id, pr_set_id, instance_id, org, repo, pr_url, pr_number, status, merge_order, merged_at, created_at FROM pr_set_members WHERE pr_set_id = ? ORDER BY merge_order
`

func (q *Queries) ListPRSetMembers(ctx context.Context, prSetID string) ([]PrSetMember, error) {
	rows, err := q.db.QueryContext(ctx, listPRSetMembers, prSetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrSetMember
	for rows.Next() {
		var i PrSetMember
		if err := rows.Scan(
			&i.ID,
			&i.PrSetID,
			&i.InstanceID,
			&i.Org,
			&i.Repo,
			&i.PrUrl,
			&i.PrNumber,
			&i.Status,
			&i.MergeOrder,
			&i.MergedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPRSets = `-- name: ListPRSets :many
SELECT id, group_name, status, deployment_order, created_at, updated_at FROM pr_sets WHERE group_name = ? ORDER BY created_at DESC
`

func (q *Queries) ListPRSets(ctx context.Context, groupName string) ([]PrSet, error) {
	rows, err := q.db.QueryContext(ctx, listPRSets, groupName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrSet
	for rows.Next() {
		var i PrSet
		if err := rows.Scan(
			&i.ID,
			&i.GroupName,
			&i.Status,
			&i.DeploymentOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listResolvedFailures = `-- name: ListResolvedFailures :many
SELECT id, instance_id, session_id, framework, test_name, file_path, assertion_text, stack_trace, input_values, error_message, code_changes, resolved, resolved_at, fix_description, fix_diff, created_at FROM test_failures
WHERE instance_id = ? AND resolved = TRUE
ORDER BY resolved_at DESC
LIMIT ?
`

type ListResolvedFailuresParams struct {
	InstanceID string
	Limit      int64
}

func (q *Queries) ListResolvedFailures(ctx context.Context, arg ListResolvedFailuresParams) ([]TestFailure, error) {
	rows, err := q.db.QueryContext(ctx, listResolvedFailures, arg.InstanceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestFailure
	for rows.Next() {
		var i TestFailure
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.SessionID,
			&i.Framework,
			&i.TestName,
			&i.FilePath,
			&i.AssertionText,
			&i.StackTrace,
			&i.InputValues,
			&i.ErrorMessage,
			&i.CodeChanges,
			&i.Resolved,
			&i.ResolvedAt,
			&i.FixDescription,
			&i.FixDiff,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByInstance = `-- name: ListSessionsByInstance :many
SELECT id, instance_id, title, status, created_at, updated_at, parent_id, model FROM sessions WHERE instance_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListSessionsByInstance(ctx context.Context, instanceID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ParentID,
			&i.Model,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStuckTasks = `-- name: ListStuckTasks :many
SELECT id, instance_id, issue_number, issue_url, title, status, session_id, branch_name, pr_url, last_activity_at, created_at, updated_at FROM tasks
WHERE instance_id = ? AND status = 'active'
AND last_activity_at < datetime('now', '-' || cast(? as text) || ' seconds')
`

type ListStuckTasksParams struct {
	InstanceID string
	Column2    string
}

func (q *Queries) ListStuckTasks(ctx context.Context, arg ListStuckTasksParams) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listStuckTasks, arg.InstanceID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.IssueNumber,
			&i.IssueUrl,
			&i.Title,
			&i.Status,
			&i.SessionID,
			&i.BranchName,
			&i.PrUrl,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByInstance = `-- name: ListTasksByInstance :many
SELECT id, instance_id, issue_number, issue_url, title, status, session_id, branch_name, pr_url, last_activity_at, created_at, updated_at FROM tasks WHERE instance_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListTasksByInstance(ctx context.Context, instanceID string) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, listTasksByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.IssueNumber,
			&i.IssueUrl,
			&i.Title,
			&i.Status,
			&i.SessionID,
			&i.BranchName,
			&i.PrUrl,
			&i.LastActivityAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestFailuresByInstance = `-- name: ListTestFailuresByInstance :many
SELECT id, instance_id, session_id, framework, test_name, file_path, assertion_text, stack_trace, input_values, error_message, code_changes, resolved, resolved_at, fix_description, fix_diff, created_at FROM test_failures
WHERE instance_id = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListTestFailuresByInstanceParams struct {
	InstanceID string
	Limit      int64
}

func (q *Queries) ListTestFailuresByInstance(ctx context.Context, arg ListTestFailuresByInstanceParams) ([]TestFailure, error) {
	rows, err := q.db.QueryContext(ctx, listTestFailuresByInstance, arg.InstanceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestFailure
	for rows.Next() {
		var i TestFailure
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.SessionID,
			&i.Framework,
			&i.TestName,
			&i.FilePath,
			&i.AssertionText,
			&i.StackTrace,
			&i.InputValues,
			&i.ErrorMessage,
			&i.CodeChanges,
			&i.Resolved,
			&i.ResolvedAt,
			&i.FixDescription,
			&i.FixDiff,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnresolvedFailures = `-- name: ListUnresolvedFailures :many
SELECT id, instance_id, session_id, framework, test_name, file_path, assertion_text, stack_trace, input_values, error_message, code_changes, resolved, resolved_at, fix_description, fix_diff, created_at FROM test_failures
WHERE instance_id = ? AND resolved = FALSE
ORDER BY created_at DESC
`

func (q *Queries) ListUnresolvedFailures(ctx context.Context, instanceID string) ([]TestFailure, error) {
	rows, err := q.db.QueryContext(ctx, listUnresolvedFailures, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TestFailure
	for rows.Next() {
		var i TestFailure
		if err := rows.Scan(
			&i.ID,
			&i.InstanceID,
			&i.SessionID,
			&i.Framework,
			&i.TestName,
			&i.FilePath,
			&i.AssertionText,
			&i.StackTrace,
			&i.InputValues,
			&i.ErrorMessage,
			&i.CodeChanges,
			&i.Resolved,
			&i.ResolvedAt,
			&i.FixDescription,
			&i.FixDiff,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveTestFailure = `-- name: ResolveTestFailure :exec
UPDATE test_failures
SET resolved = TRUE, resolved_at = datetime('now', 'utc'), fix_description = ?, fix_diff = ?
WHERE id = ?
`

type ResolveTestFailureParams struct {
	FixDescription sql.NullString
	FixDiff        sql.NullString
	ID             string
}

func (q *Queries) ResolveTestFailure(ctx context.Context, arg ResolveTestFailureParams) error {
	_, err := q.db.ExecContext(ctx, resolveTestFailure, arg.FixDescription, arg.FixDiff, arg.ID)
	return err
}

const retireFlockAgentSession = `-- name: RetireFlockAgentSession :exec
UPDATE flock_agent_sessions SET status = 'retired', updated_at = datetime('now') WHERE id = ?
`

func (q *Queries) RetireFlockAgentSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, retireFlockAgentSession, id)
	return err
}

const retireOrchestratorSession = `-- name: RetireOrchestratorSession :exec
UPDATE orchestrator_sessions
SET status = 'retired', updated_at = datetime('now')
WHERE id = ?
`

func (q *Queries) RetireOrchestratorSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, retireOrchestratorSession, id)
	return err
}

const updateCrossRepoTaskStatus = `-- name: UpdateCrossRepoTaskStatus :exec
UPDATE cross_repo_tasks SET status = ?, updated_at = datetime('now', 'utc') WHERE id = ?
`

type UpdateCrossRepoTaskStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateCrossRepoTaskStatus(ctx context.Context, arg UpdateCrossRepoTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCrossRepoTaskStatus, arg.Status, arg.ID)
	return err
}

const updateFlockAgentSession = `-- name: UpdateFlockAgentSession :exec
UPDATE flock_agent_sessions SET session_id = ?, status = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateFlockAgentSessionParams struct {
	SessionID string
	Status    string
	ID        string
}

func (q *Queries) UpdateFlockAgentSession(ctx context.Context, arg UpdateFlockAgentSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateFlockAgentSession, arg.SessionID, arg.Status, arg.ID)
	return err
}

const updateInstanceHeartbeatHash = `-- name: UpdateInstanceHeartbeatHash :exec
UPDATE instances SET heartbeat_hash = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateInstanceHeartbeatHashParams struct {
	HeartbeatHash string
	ID            string
}

func (q *Queries) UpdateInstanceHeartbeatHash(ctx context.Context, arg UpdateInstanceHeartbeatHashParams) error {
	_, err := q.db.ExecContext(ctx, updateInstanceHeartbeatHash, arg.HeartbeatHash, arg.ID)
	return err
}

const updateInstanceStatus = `-- name: UpdateInstanceStatus :exec
UPDATE instances SET status = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateInstanceStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateInstanceStatus(ctx context.Context, arg UpdateInstanceStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateInstanceStatus, arg.Status, arg.ID)
	return err
}

const updateManifestValidation = `-- name: UpdateManifestValidation :exec
UPDATE repo_manifests SET valid = ?, validation_error = ?, updated_at = datetime('now', 'utc') WHERE id = ?
`

type UpdateManifestValidationParams struct {
	Valid           bool
	ValidationError sql.NullString
	ID              string
}

func (q *Queries) UpdateManifestValidation(ctx context.Context, arg UpdateManifestValidationParams) error {
	_, err := q.db.ExecContext(ctx, updateManifestValidation, arg.Valid, arg.ValidationError, arg.ID)
	return err
}

const updatePRSetMemberMerged = `-- name: UpdatePRSetMemberMerged :exec
UPDATE pr_set_members SET status = 'merged', merged_at = datetime('now', 'utc') WHERE id = ?
`

func (q *Queries) UpdatePRSetMemberMerged(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updatePRSetMemberMerged, id)
	return err
}

const updatePRSetMemberStatus = `-- name: UpdatePRSetMemberStatus :exec
UPDATE pr_set_members SET status = ?, updated_at = datetime('now', 'utc') WHERE id = ?
`

type UpdatePRSetMemberStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdatePRSetMemberStatus(ctx context.Context, arg UpdatePRSetMemberStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePRSetMemberStatus, arg.Status, arg.ID)
	return err
}

const updatePRSetStatus = `-- name: UpdatePRSetStatus :exec
UPDATE pr_sets SET status = ?, updated_at = datetime('now', 'utc') WHERE id = ?
`

type UpdatePRSetStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdatePRSetStatus(ctx context.Context, arg UpdatePRSetStatusParams) error {
	_, err := q.db.ExecContext(ctx, updatePRSetStatus, arg.Status, arg.ID)
	return err
}

const updateSessionModel = `-- name: UpdateSessionModel :exec
UPDATE sessions SET model = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateSessionModelParams struct {
	Model sql.NullString
	ID    string
}

func (q *Queries) UpdateSessionModel(ctx context.Context, arg UpdateSessionModelParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionModel, arg.Model, arg.ID)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE sessions SET status = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateSessionStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionStatus, arg.Status, arg.ID)
	return err
}

const updateTaskActivity = `-- name: UpdateTaskActivity :exec
UPDATE tasks SET last_activity_at = datetime('now'), updated_at = datetime('now') WHERE id = ?
`

func (q *Queries) UpdateTaskActivity(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateTaskActivity, id)
	return err
}

const updateTaskPR = `-- name: UpdateTaskPR :exec
UPDATE tasks SET pr_url = ?, status = 'completed', updated_at = datetime('now') WHERE id = ?
`

type UpdateTaskPRParams struct {
	PrUrl string
	ID    string
}

func (q *Queries) UpdateTaskPR(ctx context.Context, arg UpdateTaskPRParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskPR, arg.PrUrl, arg.ID)
	return err
}

const updateTaskSession = `-- name: UpdateTaskSession :exec
UPDATE tasks SET session_id = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateTaskSessionParams struct {
	SessionID string
	ID        string
}

func (q *Queries) UpdateTaskSession(ctx context.Context, arg UpdateTaskSessionParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskSession, arg.SessionID, arg.ID)
	return err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks SET status = ?, updated_at = datetime('now') WHERE id = ?
`

type UpdateTaskStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateTaskStatus, arg.Status, arg.ID)
	return err
}

const updateWorktreeActivity = `-- name: UpdateWorktreeActivity :exec
UPDATE worktree_metadata
SET last_activity_at = datetime('now', 'utc'), updated_at = datetime('now', 'utc')
WHERE id = ?
`

func (q *Queries) UpdateWorktreeActivity(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, updateWorktreeActivity, id)
	return err
}

const updateWorktreeDeleted = `-- name: UpdateWorktreeDeleted :exec
UPDATE worktree_metadata
SET status = 'completed', deletion_reason = ?, deleted_at = datetime('now', 'utc'), updated_at = datetime('now', 'utc')
WHERE id = ?
`

type UpdateWorktreeDeletedParams struct {
	DeletionReason string
	ID             string
}

func (q *Queries) UpdateWorktreeDeleted(ctx context.Context, arg UpdateWorktreeDeletedParams) error {
	_, err := q.db.ExecContext(ctx, updateWorktreeDeleted, arg.DeletionReason, arg.ID)
	return err
}

const updateWorktreeDiskUsage = `-- name: UpdateWorktreeDiskUsage :exec
UPDATE worktree_metadata
SET disk_usage_bytes = ?, has_uncommitted_changes = ?, updated_at = datetime('now', 'utc')
WHERE id = ?
`

type UpdateWorktreeDiskUsageParams struct {
	DiskUsageBytes        int64
	HasUncommittedChanges int64
	ID                    string
}

func (q *Queries) UpdateWorktreeDiskUsage(ctx context.Context, arg UpdateWorktreeDiskUsageParams) error {
	_, err := q.db.ExecContext(ctx, updateWorktreeDiskUsage, arg.DiskUsageBytes, arg.HasUncommittedChanges, arg.ID)
	return err
}

const updateWorktreeStatus = `-- name: UpdateWorktreeStatus :exec
UPDATE worktree_metadata
SET status = ?, updated_at = datetime('now', 'utc')
WHERE id = ?
`

type UpdateWorktreeStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) UpdateWorktreeStatus(ctx context.Context, arg UpdateWorktreeStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateWorktreeStatus, arg.Status, arg.ID)
	return err
}

const upsertRepoManifest = `-- name: UpsertRepoManifest :one

INSERT INTO repo_manifests (id, instance_id, org, repo, group_name, manifest_json)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(instance_id, org, repo) DO UPDATE SET
  group_name = excluded.group_name,
  manifest_json = excluded.manifest_json,
  valid = TRUE,
  validation_error = NULL,
  updated_at = datetime('now', 'utc')
RETURNING id, instance_id, org, repo, group_name, manifest_json, valid, validation_error, created_at, updated_at
`

type UpsertRepoManifestParams struct {
	ID           string
	InstanceID   string
	Org          string
	Repo         string
	GroupName    string
	ManifestJson string
}

// Repository manifest queries
func (q *Queries) UpsertRepoManifest(ctx context.Context, arg UpsertRepoManifestParams) (RepoManifest, error) {
	row := q.db.QueryRowContext(ctx, upsertRepoManifest,
		arg.ID,
		arg.InstanceID,
		arg.Org,
		arg.Repo,
		arg.GroupName,
		arg.ManifestJson,
	)
	var i RepoManifest
	err := row.Scan(
		&i.ID,
		&i.InstanceID,
		&i.Org,
		&i.Repo,
		&i.GroupName,
		&i.ManifestJson,
		&i.Valid,
		&i.ValidationError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (id, instance_id, parent_id, title, status)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  title = excluded.title,
  updated_at = datetime('now')
`

type UpsertSessionParams struct {
	ID         string
	InstanceID string
	ParentID   string
	Title      string
	Status     string
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSession,
		arg.ID,
		arg.InstanceID,
		arg.ParentID,
		arg.Title,
		arg.Status,
	)
	return err
}
