// Code generated by sqlc. DO NOT EDIT.

package sqlc

import (
	"context"
)

const createInstance = `-- name: CreateInstance :one
INSERT INTO instances (id, pid, port, working_directory, status)
VALUES (?, ?, ?, ?, ?)
RETURNING id, pid, port, working_directory, status, created_at, updated_at
`

func (q *Queries) CreateInstance(ctx context.Context, id string, pid int64, port int64, workingDirectory string, status string) (Instance, error) {
	row := q.db.QueryRowContext(ctx, createInstance, id, pid, port, workingDirectory, status)
	var i Instance
	err := row.Scan(&i.ID, &i.Pid, &i.Port, &i.WorkingDirectory, &i.Status, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (id, instance_id, title, status)
VALUES (?, ?, ?, ?)
RETURNING id, instance_id, title, status, created_at, updated_at
`

func (q *Queries) CreateSession(ctx context.Context, id string, instanceID string, title string, status string) (Session, error) {
	row := q.db.QueryRowContext(ctx, createSession, id, instanceID, title, status)
	var s Session
	err := row.Scan(&s.ID, &s.InstanceID, &s.Title, &s.Status, &s.CreatedAt, &s.UpdatedAt)
	return s, err
}

const deleteInstance = `-- name: DeleteInstance :exec
DELETE FROM instances WHERE id = ?
`

func (q *Queries) DeleteInstance(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteInstance, id)
	return err
}

const deleteSessionsByInstance = `-- name: DeleteSessionsByInstance :exec
DELETE FROM sessions WHERE instance_id = ?
`

func (q *Queries) DeleteSessionsByInstance(ctx context.Context, instanceID string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionsByInstance, instanceID)
	return err
}

const getInstance = `-- name: GetInstance :one
SELECT id, pid, port, working_directory, status, created_at, updated_at FROM instances WHERE id = ?
`

func (q *Queries) GetInstance(ctx context.Context, id string) (Instance, error) {
	row := q.db.QueryRowContext(ctx, getInstance, id)
	var i Instance
	err := row.Scan(&i.ID, &i.Pid, &i.Port, &i.WorkingDirectory, &i.Status, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, instance_id, title, status, created_at, updated_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var s Session
	err := row.Scan(&s.ID, &s.InstanceID, &s.Title, &s.Status, &s.CreatedAt, &s.UpdatedAt)
	return s, err
}

const listInstances = `-- name: ListInstances :many
SELECT id, pid, port, working_directory, status, created_at, updated_at FROM instances ORDER BY created_at DESC
`

func (q *Queries) ListInstances(ctx context.Context) ([]Instance, error) {
	rows, err := q.db.QueryContext(ctx, listInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instance
	for rows.Next() {
		var i Instance
		if err := rows.Scan(&i.ID, &i.Pid, &i.Port, &i.WorkingDirectory, &i.Status, &i.CreatedAt, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	return items, rows.Err()
}

const listSessionsByInstance = `-- name: ListSessionsByInstance :many
SELECT id, instance_id, title, status, created_at, updated_at FROM sessions WHERE instance_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListSessionsByInstance(ctx context.Context, instanceID string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByInstance, instanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var s Session
		if err := rows.Scan(&s.ID, &s.InstanceID, &s.Title, &s.Status, &s.CreatedAt, &s.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, s)
	}
	return items, rows.Err()
}

const markStaleInstancesStopped = `-- name: MarkStaleInstancesStopped :exec
UPDATE instances SET status = 'stopped', updated_at = datetime('now') WHERE status IN ('starting', 'running')
`

func (q *Queries) MarkStaleInstancesStopped(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, markStaleInstancesStopped)
	return err
}

const updateInstancePort = `-- name: UpdateInstancePort :exec
UPDATE instances SET port = ?, updated_at = datetime('now') WHERE id = ?
`

func (q *Queries) UpdateInstancePort(ctx context.Context, port int64, id string) error {
	_, err := q.db.ExecContext(ctx, updateInstancePort, port, id)
	return err
}

const updateInstanceStatus = `-- name: UpdateInstanceStatus :exec
UPDATE instances SET status = ?, updated_at = datetime('now') WHERE id = ?
`

func (q *Queries) UpdateInstanceStatus(ctx context.Context, status string, id string) error {
	_, err := q.db.ExecContext(ctx, updateInstanceStatus, status, id)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE sessions SET status = ?, updated_at = datetime('now') WHERE id = ?
`

func (q *Queries) UpdateSessionStatus(ctx context.Context, status string, id string) error {
	_, err := q.db.ExecContext(ctx, updateSessionStatus, status, id)
	return err
}
